### ISSUE TITLE
Cannot find import FiWi.cosim.BasicCosimNode;

### ISSUE THREAD

**Issue by yugushihuang** [martinlevesque/Co-MATLAB-OMNeT#1]
Hello,

I am trying to run the code, but when I import it to my OMNET++, there are lots of errors. Could you please help me with providing the "FiWi.cosim.BasicCosimNode"

Thanks in advance!
Tinker

**Comment by martinlevesque** [comment]
hey,

I don't have the full source code currently beyond that repository unfortunately, didn't touch it since a while. I believe you could rewrite the missing part.

Thanks

**Comment by yugushihuang** [comment]
Thank you very much for your quick reply, but I am pretty new to OMNET++. It would be very helpful if you could provide any resources that could be helpful.

Thanks,
Tinker

**Comment by 179416326** [comment]
Hi yugushihuang, have u solved the problem with "FiWi.cosim.BasicCosimNode"?

**Comment by yugushihuang** [comment]
> Hi yugushihuang, have u solved the problem with "FiWi.cosim.BasicCosimNode"?

Not yet. I am still learning and working on it. Cannot get it running. Are you working on the same type of problem?
